# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Meta
version:      0.01
version_from: lib/WWW/Mechanize/Meta.pm
installdirs:  site
requires:
    Test::More:                    0
    WWW::Mechanize:                1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
