--- #YAML:1.0
name:               WWW-Mechanize-Meta
version:            0.06
abstract:           Adds HEAD tag parsing to WWW::Mechanize
author:
    - Andrey Kostenko <andrey@kostenko.name>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:      0
    WWW::Mechanize:  1.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
